package exception;

public class AutoCloseObjTest {

	public static void main(String[] args) {
		// try-with-resources문과 강제예외발생
		try(AutoCloseObj obj = new AutoCloseObj()){
			throw new Exception();
		} catch(Exception e) {
			System.out.println("예외 부분입니다.");
		}
	}

}
